// Generated by Haxe 4.3.3
#ifndef INCLUDED_discord_ImageHandle
#define INCLUDED_discord_ImageHandle

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_bffcf66000ffc303_331_new)
#ifndef INCLUDED_6db1f306f8fa425f
#define INCLUDED_6db1f306f8fa425f
#include "C:/Users/Home/Documents/GitHub/discord_game_sdk/haxe/discord/_internal/ffi.h"
#endif
HX_DECLARE_CLASS1(discord,ImageHandle)

namespace discord{


class HXCPP_CLASS_ATTRIBUTES ImageHandle_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef ImageHandle_obj OBJ_;
		ImageHandle_obj();

	public:
		enum { _hx_ClassId = 0x0c7d2817 };

		void __construct( ::Dynamic type, ::Dynamic id, ::Dynamic size);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="discord.ImageHandle")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"discord.ImageHandle"); }

		inline static ::hx::ObjectPtr< ImageHandle_obj > __new( ::Dynamic type, ::Dynamic id, ::Dynamic size) {
			::hx::ObjectPtr< ImageHandle_obj > __this = new ImageHandle_obj();
			__this->__construct(type,id,size);
			return __this;
		}

		inline static ::hx::ObjectPtr< ImageHandle_obj > __alloc(::hx::Ctx *_hx_ctx, ::Dynamic type, ::Dynamic id, ::Dynamic size) {
			ImageHandle_obj *__this = (ImageHandle_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(ImageHandle_obj), true, "discord.ImageHandle"));
			*(void **)__this = ImageHandle_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_bffcf66000ffc303_331_new)
HXLINE( 332)		 ::Dynamic tmp = type;
HXDLIN( 332)		int _hx_tmp;
HXDLIN( 332)		if (::hx::IsNotNull( tmp )) {
HXLINE( 332)			_hx_tmp = ( (int)(tmp) );
            		}
            		else {
HXLINE( 332)			_hx_tmp = 0;
            		}
HXDLIN( 332)		( ( ::discord::ImageHandle)(__this) )->set_type(_hx_tmp);
HXLINE( 333)		 ::Dynamic tmp1 = id;
HXDLIN( 333)		::cpp::Int64 _hx_tmp1;
HXDLIN( 333)		if (::hx::IsNotNull( tmp1 )) {
HXLINE( 333)			_hx_tmp1 = ( (::cpp::Int64)(tmp1) );
            		}
            		else {
HXLINE( 333)			_hx_tmp1 = ( (::cpp::Int64)(0) );
            		}
HXDLIN( 333)		( ( ::discord::ImageHandle)(__this) )->set_id(_hx_tmp1);
HXLINE( 334)		 ::Dynamic tmp2 = size;
HXDLIN( 334)		unsigned int _hx_tmp2;
HXDLIN( 334)		if (::hx::IsNotNull( tmp2 )) {
HXLINE( 334)			_hx_tmp2 = ( (unsigned int)(tmp2) );
            		}
            		else {
HXLINE( 334)			_hx_tmp2 = ( (unsigned int)(0) );
            		}
HXDLIN( 334)		( ( ::discord::ImageHandle)(__this) )->set_size(_hx_tmp2);
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~ImageHandle_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("ImageHandle",43,25,70,e4); }

		 DiscordImageHandle internal_;
		int get_type();
		::Dynamic get_type_dyn();

		int set_type(int v);
		::Dynamic set_type_dyn();

		::cpp::Int64 get_id();
		::Dynamic get_id_dyn();

		::cpp::Int64 set_id(::cpp::Int64 v);
		::Dynamic set_id_dyn();

		unsigned int get_size();
		::Dynamic get_size_dyn();

		unsigned int set_size(unsigned int v);
		::Dynamic set_size_dyn();

};

} // end namespace discord

#endif /* INCLUDED_discord_ImageHandle */ 
