// Generated by Haxe 4.3.3
#ifndef INCLUDED_discord_Sku
#define INCLUDED_discord_Sku

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_6db1f306f8fa425f
#define INCLUDED_6db1f306f8fa425f
#include "C:/Users/Home/Documents/GitHub/discord_game_sdk/haxe/discord/_internal/ffi.h"
#endif
HX_DECLARE_CLASS1(discord,Sku)
HX_DECLARE_CLASS1(discord,SkuPrice)

namespace discord{


class HXCPP_CLASS_ATTRIBUTES Sku_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Sku_obj OBJ_;
		Sku_obj();

	public:
		enum { _hx_ClassId = 0x40a36791 };

		void __construct( ::Dynamic id, ::Dynamic type,::String name, ::discord::SkuPrice price);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="discord.Sku")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"discord.Sku"); }
		static ::hx::ObjectPtr< Sku_obj > __new( ::Dynamic id, ::Dynamic type,::String name, ::discord::SkuPrice price);
		static ::hx::ObjectPtr< Sku_obj > __alloc(::hx::Ctx *_hx_ctx, ::Dynamic id, ::Dynamic type,::String name, ::discord::SkuPrice price);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Sku_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Sku",bd,58,3f,00); }

		 DiscordSku internal_;
		::cpp::Int64 get_id();
		::Dynamic get_id_dyn();

		::cpp::Int64 set_id(::cpp::Int64 v);
		::Dynamic set_id_dyn();

		int get_type();
		::Dynamic get_type_dyn();

		int set_type(int v);
		::Dynamic set_type_dyn();

		::String get_name();
		::Dynamic get_name_dyn();

		::String set_name(::String v);
		::Dynamic set_name_dyn();

		 ::discord::SkuPrice _price;
		 ::discord::SkuPrice get_price();
		::Dynamic get_price_dyn();

		 ::discord::SkuPrice set_price( ::discord::SkuPrice v);
		::Dynamic set_price_dyn();

};

} // end namespace discord

#endif /* INCLUDED_discord_Sku */ 
