// Generated by Haxe 4.3.3
#ifndef INCLUDED_Test
#define INCLUDED_Test

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(Test)



class HXCPP_CLASS_ATTRIBUTES Test_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Test_obj OBJ_;
		Test_obj();

	public:
		enum { _hx_ClassId = 0x0c25ea96 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="Test")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"Test"); }

		inline static ::hx::ObjectPtr< Test_obj > __new() {
			::hx::ObjectPtr< Test_obj > __this = new Test_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< Test_obj > __alloc(::hx::Ctx *_hx_ctx) {
			Test_obj *__this = (Test_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Test_obj), false, "Test"));
			*(void **)__this = Test_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Test_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Test",72,f4,d2,37); }

		static void main();
		static ::Dynamic main_dyn();

};


#endif /* INCLUDED_Test */ 
