// Generated by Haxe 4.3.3
#include <hxcpp.h>

#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_Int64Helper
#include <haxe/Int64Helper.h>
#endif
#ifndef INCLUDED_discord_LobbySearchQuery
#include <discord/LobbySearchQuery.h>
#endif
#ifndef INCLUDED_discord_LobbyMemberTransaction
#include <discord/LobbyMemberTransaction.h>
#endif
#ifndef INCLUDED_discord_LobbyTransaction
#include <discord/LobbyTransaction.h>
#endif
#ifndef INCLUDED_discord_UserAchievement
#include <discord/UserAchievement.h>
#endif
#ifndef INCLUDED_discord_InputMode
#include <discord/InputMode.h>
#endif
#ifndef INCLUDED_discord_Sku
#include <discord/Sku.h>
#endif
#ifndef INCLUDED_discord_SkuPrice
#include <discord/SkuPrice.h>
#endif
#ifndef INCLUDED_discord_Entitlement
#include <discord/Entitlement.h>
#endif
#ifndef INCLUDED_discord_FileStat
#include <discord/FileStat.h>
#endif
#ifndef INCLUDED_discord_Rect
#include <discord/Rect.h>
#endif
#ifndef INCLUDED_discord_ImeUnderline
#include <discord/ImeUnderline.h>
#endif
#ifndef INCLUDED_discord_Lobby
#include <discord/Lobby.h>
#endif
#ifndef INCLUDED_discord_Relationship
#include <discord/Relationship.h>
#endif
#ifndef INCLUDED_discord_Presence
#include <discord/Presence.h>
#endif
#ifndef INCLUDED_discord_Activity
#include <discord/Activity.h>
#endif
#ifndef INCLUDED_discord_ActivitySecrets
#include <discord/ActivitySecrets.h>
#endif
#ifndef INCLUDED_discord_ActivityParty
#include <discord/ActivityParty.h>
#endif
#ifndef INCLUDED_discord_PartySize
#include <discord/PartySize.h>
#endif
#ifndef INCLUDED_discord_ActivityAssets
#include <discord/ActivityAssets.h>
#endif
#ifndef INCLUDED_discord_ActivityTimestamps
#include <discord/ActivityTimestamps.h>
#endif
#ifndef INCLUDED_discord_ImageDimensions
#include <discord/ImageDimensions.h>
#endif
#ifndef INCLUDED_discord_ImageHandle
#include <discord/ImageHandle.h>
#endif
#ifndef INCLUDED_discord_OAuth2Token
#include <discord/OAuth2Token.h>
#endif
#ifndef INCLUDED_discord_User
#include <discord/User.h>
#endif
#ifndef INCLUDED_discord_Core
#include <discord/Core.h>
#endif
#ifndef INCLUDED_discord_ActivityManager
#include <discord/ActivityManager.h>
#endif
#ifndef INCLUDED_Test
#include <Test.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::haxe::Log_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::Int64Helper_obj::__register();
::discord::LobbySearchQuery_obj::__register();
::discord::LobbyMemberTransaction_obj::__register();
::discord::LobbyTransaction_obj::__register();
::discord::UserAchievement_obj::__register();
::discord::InputMode_obj::__register();
::discord::Sku_obj::__register();
::discord::SkuPrice_obj::__register();
::discord::Entitlement_obj::__register();
::discord::FileStat_obj::__register();
::discord::Rect_obj::__register();
::discord::ImeUnderline_obj::__register();
::discord::Lobby_obj::__register();
::discord::Relationship_obj::__register();
::discord::Presence_obj::__register();
::discord::Activity_obj::__register();
::discord::ActivitySecrets_obj::__register();
::discord::ActivityParty_obj::__register();
::discord::PartySize_obj::__register();
::discord::ActivityAssets_obj::__register();
::discord::ActivityTimestamps_obj::__register();
::discord::ImageDimensions_obj::__register();
::discord::ImageHandle_obj::__register();
::discord::OAuth2Token_obj::__register();
::discord::User_obj::__register();
::discord::Core_obj::__register();
::discord::ActivityManager_obj::__register();
::Test_obj::__register();
::StringTools_obj::__register();
::Std_obj::__register();
::haxe::Log_obj::__boot();
}

