// Generated by Haxe 4.3.3
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"?",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/Std.hx",
"C:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Log.hx",
"C:\\HaxeToolkit\\haxe\\std/haxe/iterators/ArrayIterator.hx",
"Test.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"C:\\Users\\Home\\Documents\\GitHub\\discord_game_sdk\\?",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Std.hx",
"C:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Log.hx",
"C:\\HaxeToolkit\\haxe\\std\\haxe\\iterators\\ArrayIterator.hx",
"C:\\Users\\Home\\Documents\\GitHub\\discord_game_sdk\\Test.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Std",
"Test",
"haxe.Log",
"haxe.iterators.ArrayIterator",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
